INSERT INTO SYS_RESOURCES(ID,CODE,DISPLAY,DESCRIPTION,PARENT_CODE,TYPE,URL,SORT,ICON)
VALUES('TARGET_IMPLEMENTATION_SYSTEM','TARGET_IMPLEMENTATION_SYSTEM','目标实现系统','目标实现系统','','1','',40,'layui-icon layui-icon-flag');

INSERT INTO SYS_RESOURCES(ID,CODE,DISPLAY,DESCRIPTION,PARENT_CODE,TYPE,URL,SORT,ICON)
 VALUES('TARGET_SETTING','TARGET_SETTING','目标制定','目标制定','TARGET_IMPLEMENTATION_SYSTEM','1','/admin/login_getTestPage.do',41,'layui-icon layui-icon-edit');

INSERT INTO SYS_RESOURCES(ID,CODE,DISPLAY,DESCRIPTION,PARENT_CODE,TYPE,URL,SORT,ICON)
VALUES('TARGET_MANAGEMENT','TARGET_MANAGEMENT','目标管理','目标管理','TARGET_IMPLEMENTATION_SYSTEM','1','/admin/login_getTestPage.do',42,'layui-icon layui-icon-form');

INSERT INTO SYS_RESOURCES(ID,CODE,DISPLAY,DESCRIPTION,PARENT_CODE,TYPE,URL,SORT,ICON) 
VALUES('TARGET_ACHIEVE','TARGET_ACHIEVE','目标实现','目标实现','TARGET_IMPLEMENTATION_SYSTEM','1','/admin/login_getTestPage.do',43,'layui-icon layui-icon-release');
